### ISSUE TITLE
Concept library timeout

### ISSUE THREAD

**Issue by rouqueto** [SwanseaUniversityMedical/ConceptLibraryClient#4] opened 2023-06-22 15:31 UTC
Hi,
I have tried to use the concept library API_client in SAIL but it leads to the following error:

![image](https://github.com/SwanseaUniversityMedical/ConceptLibraryClient/assets/137425031/48e14e15-5151-4914-baf5-47f578eb28ae)

can you help?
Thanks,
Olivier

**Comment by ieuans** [comment] 2023-11-23 16:55
Legacy issue resolved in emails, caused by missing HTTP/S proxy variables after gateway monthly maintenance

**Closed as completed by ieuans** 2023-11-23 16:55 UTC
Labels: bug
